spring:
  redis:
      database: 2
      host: 10.103.60.213
      jedis:
        pool:
            max-active: 20
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
